apps/cliente/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import ClienteView, ClienteListView, ClienteUpdateView, ClienteDeleteView

urlpatterns = [
    path('criar', login_required(ClienteView.as_view()), name='cliente-criar'),
    path('', login_required(ClienteListView.as_view()), name="cliente-list"),
    path('editar/<int:pk>/', login_required(ClienteUpdateView.as_view()), name="cliente-edit"),
    path('excluir/<int:pk>/', login_required(ClienteDeleteView.as_view()), name="cliente-delete"),
]

apps/core/urls.py
from django.contrib import admin
from django.urls import path
from .views import TemplateHomeView

urlpatterns = [
    path('', TemplateHomeView.as_view(), name='home'),
]

apps/usuario/urls.py
from django.contrib import admin
from django.urls import path
from .views import signupview, userlist, userlogin, userlogout, password

urlpatterns = [
    path('registrar/', signupview, name="register"),
    path('', userlist, name="usuarios"),
    path('login/', userlogin, name="login"),
    path('deslogar/', userlogout, name="logout"),
    path('password', password, name="password"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('apps.usuario.urls')),
    path('', include('apps.core.urls')),
    path('cliente/', include('apps.cliente.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

]

apps/cliente/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=150, blank=False, null=False)
    telefone = models.CharField(max_length=15, blank=True, null=True)
    endereco = models.CharField(verbose_name="Endereço", max_length=150, blank=False, null=False)
    numero = models.IntegerField(verbose_name="Número", blank=True, null=True)
    cidade = models.CharField(max_length=100, blank=False, null=False)
    estado = models.CharField(max_length=100, blank=False, null=False)
    pais = models.CharField(verbose_name="País",max_length=100, blank=False, null=False)
    cep = models.CharField(max_length=10, blank=False, null=False)

    def __str__(self):
        return self.nome

apps/core/models.py
from django.db import models

# Create your models here.

apps/usuario/models.py
from django.db import models

# Create your models here.

apps/usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupUserForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text="Requerido. Informe um endereço válido!")

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

apps/cliente/views.py
#Django Imports
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, ModelFormMixin, DeleteView
#Local Imports
from .models import Cliente

class ClienteView(CreateView):
    model = Cliente
    fields = ['nome', 'telefone', 'endereco', 'numero', 'cidade', 'estado', 'pais', 'cep']
    success_url = '/cliente/'

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        if self.success_url:
            url = self.success_url.format(**self.object.__dict__)
        else:
            try:
                url = self.object.get_absolute_url()
            except AttributeError:
                raise ImproperlyConfigured(
                    "No URL to redirect to.  Either provide a url or define"
                    " a get_absolute_url method on the Model.")
        return url

class ClienteListView(ListView):
    model = Cliente
    template_name = 'cliente_list.html'
    msg = 'Ficha de Cadastro'

    def get_context_data(self, *, object_list=None, Cliente=Cliente):
        context = {}
        context['object_list'] = Cliente.objects.all()
        return context

class ClienteUpdateView(UpdateView):
    model = Cliente
    fields = ['nome', 'telefone', 'endereco', 'numero', 'cidade', 'estado', 'pais', 'cep']
    success_url = '/cliente/'
    pk_url_kwarg = 'pk'

class ClienteDeleteView(DeleteView):
    model = Cliente
    success_url = '/cliente/'
    pk_url_kwarg = 'pk'

apps/core/views.py
from django.conf.global_settings import LOGIN_URL
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import TemplateView

class TemplateHomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = 'Bem vindo ao Sistema'
        return context

apps/usuario/views.py
#Django imports
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm, AdminPasswordChangeForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
#Local Imports
from .forms import SignupUserForm


LOGIN_URL = '/usuario/login/'

@login_required(login_url=LOGIN_URL)
def signupview(request):
    if request.method == 'POST':
        form = SignupUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('usuarios')
    else:
        form = SignupUserForm

    return render(request, 'register.html', {'form':form})

@login_required(login_url=LOGIN_URL)
def userlist(request):
    context = {}
    usuarios = User.objects.all()
    context['usuarios'] = usuarios
    return render(request, 'list.html', context)

def userlogin(request):
    if request.method == 'POST':
        username_raw = request.POST['usuario']
        password_raw = request.POST['senha']
        user = authenticate(request, username=username_raw, password=password_raw)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/usuario/')
        else:
            return HttpResponseRedirect(LOGIN_URL)
    return render(request, 'login.html', {})

def userlogout(request):
    logout(request)
    return HttpResponseRedirect(LOGIN_URL)

@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('home')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'password.html', {'form': form})

apps/cliente/templates/cliente/cliente_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Excluir Cliente{% endblock %}


{% block css-fixo %}
<link rel="stylesheet" href="{% static 'apps/usuario/estilo_usuario.css' %}">
{% endblock %}

{% block content %}

<div class="container">

    <form action="{% url 'cliente-delete' pk=cliente.id %}" method="POST">{% csrf_token %}
        <div class="container__body">

            <div role="dialog">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Exclusão</h5>
                  </div>
                  <div class="modal-body">
                      <p>Tem certeza que deseja remover o cliente: <b>{{cliente.nome}}</b> ?</p>
                  </div>
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">TENHO CERTEZA</button>
                    <a type="button" href="{% url 'cliente-list' %}" class="btn btn-secondary">Não, cancelar.</a>
                  </div>
                </div>
              </div>
            </div>

        </div>
    </form>
</div>

{% endblock %}

apps/cliente/templates/cliente/cliente_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cadastrar Cliente{% endblock %}

{% load crispy_forms_tags %}

{% block css-fixo %}
<link rel="stylesheet" href="{% static 'apps/usuario/estilo_usuario.css' %}">
{% endblock %}

{% block content %}

<div class="container">

    <form method="post">{% csrf_token %}
        <div class="container__body">

            <h3 class="container__body__info">{{msg}}</h3>

            <div class="row">
                <div class="col-12">
                    {{form.nome|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.telefone|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.cep|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.endereco|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.numero|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.cidade|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.estado|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.pais|as_crispy_field}}
                </div>

                <button class="btn btn-primary" type="submit">SALVAR</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

{% block js-body %}
<script type="text/javascript" src="{% static 'apps/cliente/js/jquery.mask.js' %}"></script>

<script>

    $(document).ready(function(){

    //Mascaras para campos de CEP e Telefone
        $('#id_cep').mask('00000-000');
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
            onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
          }
        };
        $('#id_telefone').mask(SPMaskBehavior, spOptions);

    //Preenchimento automatico do cep

    function limpa_formulário_cep() {
                // Limpa valores do formulário de cep.
                $("#id_endereco").val("");
                $("#id_cidade").val("");
                $("#id_estado").val("");
                $("#id_pais").val("");
            }

            //Quando o campo cep perde o foco.
            $("#id_cep").blur(function() {

                //Nova variável "cep" somente com dígitos.
                var cep = $(this).val().replace(/\D/g, '');

                //Verifica se campo cep possui valor informado.
                if (cep != "") {

                    //Expressão regular para validar o CEP.
                    var validacep = /^[0-9]{8}$/;

                    //Valida o formato do CEP.
                    if(validacep.test(cep)) {

                        //Preenche os campos com "..." enquanto consulta webservice.
                        $("#id_endereco").val("...");
                        $("#id_cidade").val("...");
                        $("#id_estado").val("...");
                        $("#id_pais").val("...");

                        //Consulta o webservice viacep.com.br/
                        $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                            if (!("erro" in dados)) {
                                //Atualiza os campos com os valores da consulta.
                                $("#id_endereco").val(dados.logradouro);
                                $("#id_cidade").val(dados.localidade);
                                $("#id_estado").val(dados.uf);
                                $("#id_pais").val('Brasil');
                            } //end if.
                            else {
                                //CEP pesquisado não foi encontrado.
                                limpa_formulário_cep();
                                alert("CEP não encontrado.");
                            }
                        });
                    } //end if.
                    else {
                        //cep é inválido.
                        limpa_formulário_cep();
                        alert("Formato de CEP inválido.");
                    }
                } //end if.
                else {
                    //cep sem valor, limpa formulário.
                    limpa_formulário_cep();
                }
            });


    })

</script>

{% endblock %}

apps/cliente/templates/cliente/cliente_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Clientes{% endblock %}

{% block css-fixo %}
<link rel="stylesheet" href="{% static 'apps/usuario/estilo_usuario.css' %}">
{% endblock %}
{% block content %}

<div class="container">
<div class="register__container__body">
    <h1 class="container__body__info">Lista de Clientes</h1>
    <a class="btn btn-primary" id="buttonRegister" href="{% url 'cliente-criar' %}">Cadastrar <i class="fas fa-user-plus"></i></a>
<div class="table-responsive">
    <table class="table">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Telefone</th>
      <th scope="col">Endereço</th>
      <th scope="col">Cidade</th>
      <th scope="col">Estado</th>
      <th scope="col">CEP</th>
      <th scope="col">Opções</th>
    </tr>
  </thead>
  <tbody>

  {% for cliente in object_list %}
    <tr>
      <td>{{cliente.nome}}</td>
      <td>{{cliente.telefone}}</td>
      <td>{{cliente.endereco}}</td>
      <td>{{cliente.cidade}}</td>
      <td>{{cliente.estado}}</td>
      <td>{{cliente.cep}}</td>
      <td>
        <a type="button" href="{% url 'cliente-edit' pk=cliente.pk %}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
        <a type="button" href="{% url 'cliente-delete' pk=cliente.pk %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
      </td>
    </tr>

  {% endfor %}

  </tbody>
</table>
</div>
</div>
</div>


{% endblock %}

apps/usuario/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Usuários{% endblock %}

{% block css-fixo %}
<link rel="stylesheet" href="{% static 'apps/usuario/estilo_usuario.css' %}">
{% endblock %}
{% block content %}

<div class="container">
<div class="register__container__body">
    <h1 class="container__body__info">Lista de usuários</h1>
    <a class="btn btn-primary" id="buttonRegister" href="{% url 'register' %}">Cadastrar <i class="fas fa-user-plus"></i></a>
<div class="table-responsive">
    <table class="table">
  <thead>
    <tr>
        <th>#</th>
      <th scope="col">Usuário</th>
      <th scope="col">E-mail</th>
    </tr>
  </thead>
  <tbody>

  {% for usuario in usuarios %}
    <tr>
        <td>{{usuario.id}}</td>
      <td>{{usuario.username}}</td>
      <td>{{usuario.email}}</td>
    </tr>
  {% endfor %}

  </tbody>
</table>
</div>
</div>
</div>


{% endblock %}

apps/usuario/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% load crispy_forms_tags %}

{% block css-fixo %}
<link rel="stylesheet" href="{% static 'apps/usuario/login.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-social.css' %}">
{% endblock %}

{% block nav %}
{% endblock %}

{% block content %}


    <form class="form-signin" method="post">{% csrf_token %}
        <img class="mb-4" src="{% static 'imagens/logos/user-solid.svg' %}" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Login</h1>
        {% if user.is_authenticated %}
        <span>Atenção: Usuário <b>{{user.username}}</b> está logado.
            <a href="{% url 'home' %}">clique aqui</a> para ir para home</span>
        {% else %}

        <input type="text" id="id_usuario" name="usuario" class="form-control" placeholder="Usuário" required autofocus>
      <label for="id_usuario" class="sr-only">Usuário</label>

        <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha" required>
        <label for="id_senha" class="sr-only">Password</label>

      <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>

        {% endif %}

    </form>


{% endblock %}

apps/usuario/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cadastrar Usuário{% endblock %}

{% load crispy_forms_tags %}

{% block css-fixo %}
<link rel="stylesheet" href="{% static 'apps/usuario/estilo_usuario.css' %}">
{% endblock %}

{% block content %}

<div class="container">

    <form method="post">{% csrf_token %}
        <div class="container__body">

            <h3 class="container__body__info">Ficha de Cadastro</h3>

            <div class="row">
                <div class="col-12">
                    {{form.username|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.email|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.password1|as_crispy_field}}
                </div>
                <div class="col-12">
                    {{form.password2|as_crispy_field}}
                </div>

                <button class="btn btn-primary" type="submit">CADASTRAR</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    {% block css-fixo %}
    {% endblock %}

</head>
<body>

{% block css-local %}
{% endblock %}

{% block nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Bem vindo: {% if user.is_authenticated %} <b>{{user.username}}</b>
            {% else %}
            usuário anônimo
            {% endif%}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'usuarios' %}">Usuário</a>
        <a class="nav-item nav-link" href="{% url 'cliente-list' %}">Cliente</a>
        <a class="nav-item nav-link" style="float:right" href="{% url 'logout' %}">Sair</a>
        {% else %}

        <a class="nav-item nav-link" style="float:right" href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}

{% endblock %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Atenção: <b>{{user.username}}</b>!</strong> {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"> </script>
{% block js-body %}

{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block css-fixo %}
<link rel="stylesheet" href="{% static 'apps/core/core_estilo.css' %}">
{% endblock %}
{% block content %}

<div class="container">
        <div class="containerCentral">
            <h1 class="containerCentral__title">{{msg}}</h1>
            <h3 class="containerCentral__subtitle">Escolha uma das opções abaixo: </h3>
        </div>
        <div class="row containerCentral__row">
            <div class="col">
                <a href="{% url 'usuarios' %}" class="btn btn-primary containerCentral__title__btn">Usuários</a>
            </div>
            <div class="col">
                <a href="{% url 'cliente-list' %}" class="btn btn-primary containerCentral__title__btn">Clientes</a>
            </div>
        </div>
</div>


{% endblock %}